import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useSettingsStore } from '../state/settingsStore';
export function SettingsWindow() {
    const { theme, setTheme, wallpaperIndex, setWallpaperIndex, scale, setScale } = useSettingsStore();
    return (_jsxs("div", { className: "p-4 text-black dark:text-white space-y-6", children: [_jsxs("section", { children: [_jsx("h2", { className: "font-semibold mb-2", children: "Appearance" }), _jsxs("div", { className: "flex items-center gap-3", children: [_jsxs("label", { className: "flex items-center gap-2", children: [_jsx("input", { type: "radio", name: "theme", value: "light", checked: theme === 'light', onChange: () => setTheme('light') }), " Light"] }), _jsxs("label", { className: "flex items-center gap-2", children: [_jsx("input", { type: "radio", name: "theme", value: "dark", checked: theme === 'dark', onChange: () => setTheme('dark') }), " Dark"] })] })] }), _jsxs("section", { children: [_jsx("h2", { className: "font-semibold mb-2", children: "Wallpaper" }), _jsx("div", { className: "flex items-center gap-3", children: [0, 1, 2].map((i) => (_jsx("button", { className: `w-20 h-12 rounded overflow-hidden ring-1 ring-black/10 dark:ring-white/10 ${wallpaperIndex === i ? 'outline outline-2 outline-blue-400' : ''}`, style: {
                                backgroundImage: `url(wallpapers/wallpaper-${i}.jpg)`,
                                backgroundSize: 'cover',
                                backgroundPosition: 'center',
                            }, onClick: () => setWallpaperIndex(i), "aria-label": `Wallpaper ${i + 1}`, title: `Wallpaper ${i + 1}` }, i))) })] }), _jsxs("section", { children: [_jsx("h2", { className: "font-semibold mb-2", children: "Scale" }), _jsx("div", { className: "flex items-center gap-3", children: [1, 1.25, 1.5].map((s) => (_jsxs("label", { className: "flex items-center gap-2", children: [_jsx("input", { type: "radio", name: "scale", value: s, checked: scale === s, onChange: () => setScale(s) }), " ", Math.round(s * 100), "%"] }, s))) })] })] }));
}
